export type ProfileLanguage = 'en' | 'hi';

export function getProfileCopy(language: ProfileLanguage) {
  if (language === 'hi') {
    return {
      title: 'मेरा प्रोफ़ाइल',
      subtitle: 'एक नज़र में आपकी सीखने की प्रगति',
      tabs: {
        overview: 'ओवरव्यू',
        insights: 'सीखने की अंतर्दृष्टि',
        activity: 'गतिविधि',
        saved: 'सहेजे गए',
        goals: 'लक्ष्य और सेटिंग्स',
      },
      editProfile: 'प्रोफ़ाइल संपादित करें',
      setTargetExam: 'लक्ष्य परीक्षा सेट करें',
      examIn: 'परीक्षा में',
      examCountdownLabel: 'परीक्षा काउंटडाउन',
      examCountdownTitle: 'आपकी परीक्षा तक शेष समय',
      examLeft: 'शेष',
      examHr: 'घं',
      examMin: 'मि',
      examRemaining: 'शेष',
      examDayReached: 'परीक्षा का दिन',
      examDatePassed: 'परीक्षा की तारीख बीत चुकी है',
      setExamDate: 'परीक्षा तारीख सेट करें',
      examDateLabel: 'परीक्षा की तारीख',
      changeExamAndDate: 'परीक्षा और तारीख बदलें',
      changeExamGoalTitle: 'परीक्षा लक्ष्य बदलें',
      chooseExam: 'अपनी लक्ष्य परीक्षा चुनें',
      otherExam: 'अन्य (परीक्षा का नाम लिखें)',
      otherExamPlaceholder: 'जैसे SSC CGL, State PCS…',
      examsLoadError: 'परीक्षाएँ लोड नहीं हो सकीं। नाम मैन्युअल लिखें।',
      searchExams: 'परीक्षा, राज्य या स्तर से खोजें…',
      noExamsFound: 'कोई परीक्षा नहीं मिली।',
      joined: 'शामिल',
      profileComplete: 'प्रोफ़ाइल पूर्ण',
      continuePractice: 'अभ्यास जारी रखें',
      dailyGoal: 'दैनिक लक्ष्य',
      dayStreak: 'दिन की लकीर',
      questions: 'प्रश्न',
      accuracy: 'सटीकता',
      streak: 'लकीर',
      studyTime: 'अध्ययन समय',
      days: 'दिन',
    day: 'दिन',
      thisWeek: 'इस सप्ताह',
      questionsCompleted: 'प्रश्न पूरे',
      examReadiness: 'परीक्षा तैयारी',
      coverage: 'कवरेज',
      consistency: 'निरंतरता',
      howCalculated: 'यह कैसे गिना जाता है',
      readinessLocked: `परीक्षा तैयारी अनलॉक करने के लिए कम से कम 10 प्रश्न पूरे करें।`,
      continueLearning: 'सीखना जारी रखें',
      reviewTopic: 'विषय की समीक्षा करें',
      startFirstPractice: 'अपना पहला अभ्यास शुरू करें',
      startFirstPracticeHint: 'विषयों से प्रैक्टिस शुरू करें — आपकी सिफारिशें यहाँ दिखेंगी।',
      browseSubjects: 'विषय देखें',
      recentActivity: 'हाल की गतिविधि',
      noActivity: 'अभी तक कोई गतिविधि नहीं',
      correct: 'सही',
      mistakesToReview: 'समीक्षा के लिए गलतियाँ',
      loadError: 'प्रोफ़ाइल डेटा लोड नहीं हो सका। कृपया पुनः प्रयास करें।',
      retry: 'पुनः प्रयास',
      saveChanges: 'परिवर्तन सहेजें',
      saving: 'सहेजा जा रहा है…',
      bio: 'परिचय',
      country: 'देश',
      targetExam: 'लक्ष्य परीक्षा',
      editProfileTitle: 'प्रोफ़ाइल संपादित करें',
      close: 'बंद करें',
      noPracticeYet: 'अभी तक कोई अभ्यास डेटा नहीं है। विषय चुनकर प्रैक्टिस शुरू करें।',
      comingSoon: 'जल्द आ रहा है',
      chartSummary: 'साप्ताहिक प्रश्न गतिविधि',
    } as const;
  }

  return {
    title: 'My Profile',
    subtitle: 'Your learning progress at a glance',
    tabs: {
      overview: 'Overview',
      insights: 'Learning Insights',
      activity: 'Activity',
      saved: 'Saved',
      goals: 'Goals & Settings',
    },
    editProfile: 'Edit profile',
    setTargetExam: 'Set target exam',
    examIn: 'Exam in',
    examCountdownLabel: 'EXAM COUNTDOWN',
    examCountdownTitle: 'Time remaining until your exam',
    examLeft: 'left',
    examHr: 'hr',
    examMin: 'min',
    examRemaining: 'remaining',
    examDayReached: 'Exam day',
    examDatePassed: 'Exam date passed',
    setExamDate: 'Set exam date',
    examDateLabel: 'Exam date',
    changeExamAndDate: 'Change exam & date',
    changeExamGoalTitle: 'Change exam goal',
    chooseExam: 'Choose your target exam',
    otherExam: 'Other (type your exam)',
    otherExamPlaceholder: 'e.g. SSC CGL, State PCS…',
    examsLoadError: 'Could not load exams. Type your exam name below.',
    searchExams: 'Search exams by name, state or stage…',
    noExamsFound: 'No exams match your search.',
    joined: 'Joined',
    profileComplete: 'profile complete',
    continuePractice: 'Continue Practice',
    dailyGoal: 'Daily goal',
    dayStreak: 'day streak',
    questions: 'Questions',
    accuracy: 'Accuracy',
    streak: 'Streak',
    studyTime: 'Study time',
    days: 'days',
    day: 'day',
    thisWeek: 'This week',
    questionsCompleted: 'questions completed',
    examReadiness: 'Exam readiness',
    coverage: 'Coverage',
    consistency: 'Consistency',
    howCalculated: 'How this is calculated',
    readinessLocked: 'Complete at least 10 questions to unlock exam readiness.',
    continueLearning: 'Continue learning',
    reviewTopic: 'Review topic',
    startFirstPractice: 'Start your first practice',
    startFirstPracticeHint: 'Pick a subject to begin — recommendations will appear here as you practice.',
    browseSubjects: 'Browse subjects',
    recentActivity: 'Recent activity',
    noActivity: 'No activity yet',
    correct: 'correct',
    mistakesToReview: 'mistakes to review',
    loadError: 'Could not load profile data. Please try again.',
    retry: 'Retry',
    saveChanges: 'Save Changes',
    saving: 'Saving…',
    bio: 'Bio',
    country: 'Country',
    targetExam: 'Target Exam',
    editProfileTitle: 'Edit Profile',
    close: 'Close',
    noPracticeYet: 'No practice data yet. Start practicing from Subjects — your progress will appear here.',
    comingSoon: 'Coming soon',
    chartSummary: 'Weekly question activity',
  } as const;
}

export type ProfileCopy = ReturnType<typeof getProfileCopy>;
