import type { ProfileLanguage } from './profileCopy';
import type { ActivityPeriodDays } from '@/lib/profileActivityTypes';

export type ProfileActivityCopy = ReturnType<typeof getProfileActivityCopy>;

export function getProfileActivityCopy(language: ProfileLanguage) {
  if (language === 'hi') {
    return {
      title: 'गतिविधि और प्रदर्शन',
      subtitle: 'अपने अभ्यास, सटीकता और अध्ययन समय को ट्रैक करें',
      periodLabel: 'समय अवधि',
      period7: '7 दिन',
      period30: '30 दिन',
      period90: '90 दिन',
      periodAll: 'सभी',
      periodSelectedHint: 'चयनित अवधि के आंकड़े — लकीर जीवनकाल की है',
      uniqueQuestions: 'अद्वितीय प्रश्न',
      correct: 'सही',
      incorrect: 'गलत',
      avgAnswerTime: 'औसत उत्तर समय',
      notRecorded: 'दर्ज नहीं',
      accuracyTrend: 'सटीकता प्रवृत्ति',
      currentAccuracy: (pct: number) => `${pct}% वर्तमान सटीकता`,
      changePoints: (delta: number) =>
        delta >= 0 ? `+${delta} प्रतिशत अंक पिछली अवधि से` : `${delta} प्रतिशत अंक पिछली अवधि से`,
      noPriorPeriod: 'तुलना के लिए पिछली अवधि में कोई डेटा नहीं',
      chartSummary: 'सटीकता प्रवृत्ति सारांश',
      noChartData: 'इस अवधि में कोई प्रथम-प्रयास डेटा नहीं',
      improvementAfterRetry: 'पुनः प्रयास के बाद सुधार',
      firstAttempt: 'पहला प्रयास',
      afterRevision: 'संशोधन के बाद',
      improvementPoints: (delta: number) =>
        delta >= 0 ? `+${delta} प्रतिशत अंक` : `${delta} प्रतिशत अंक`,
      mistakesCorrected: (count: number) => `${count} गलतियाँ सुधरीं`,
      cohortSample: (count: number) => `${count} पुनः प्रयास प्रश्नों पर आधारित`,
      retryLockedTitle: 'अभी पर्याप्त पुनः प्रयास डेटा नहीं',
      retryLockedHint: 'पहले छूटे प्रश्नों का पुनः प्रयास करें — यह अंतर्दृष्टि अनलॉक होगी।',
      timeConsistency: 'समय और निरंतरता',
      recordedAnswerTime: 'दर्ज उत्तर समय',
      activeDays: 'सक्रिय दिन',
      currentStreak: 'वर्तमान लकीर',
      longestStreak: 'सबसे लंबी लकीर',
      streakDays: (count: number) => `${count} दिन`,
      studyTimeChart: 'अध्ययन समय (मिनट)',
      studyTimeChartHint: 'दर्ज उत्तर अवधि से',
      noTimeData: 'इस अवधि में कोई दर्ज समय नहीं',
      practiceMix: 'अभ्यास मिश्रण',
      difficultyLevel: 'कठिनाई स्तर',
      subjectMix: 'विषय वितरण',
      examMixOmitted: 'परीक्षा टैग ओवरलैप होते हैं — विषय वितरण दिखाया गया',
      recentActivity: 'हाल की अभ्यास गतिविधि',
      session: 'गतिविधि',
      score: 'स्कोर',
      accuracy: 'सटीकता',
      time: 'समय',
      actions: 'कार्रवाई',
      view: 'देखें',
      review: 'समीक्षा',
      noRecentActivity: 'इस अवधि में कोई अभ्यास गतिविधि नहीं',
      noAttempts: 'अभी तक कोई अभ्यास डेटा नहीं। गतिविधि देखने के लिए अभ्यास शुरू करें।',
      browseSubjects: 'विषय देखें',
      loadError: 'गतिविधि डेटा लोड नहीं हो सका। कृपया पुनः प्रयास करें।',
      retry: 'पुनः प्रयास',
      firstAttemptHint: 'प्रथम-प्रयास सटीकता — पुनः प्रयास शामित नहीं',
      lifetimeMetric: 'जीवनकाल',
      periodMetric: 'चयनित अवधि',
      percentLabel: (pct: number) => `${pct}%`,
      attemptsOnDay: (count: number) => `${count} प्रयास`,
    } as const;
  }

  return {
    title: 'Activity & Performance',
    subtitle: 'Track your practice, accuracy and study time',
    periodLabel: 'Time period',
    period7: '7 days',
    period30: '30 days',
    period90: '90 days',
    periodAll: 'All time',
    periodSelectedHint: 'Metrics follow the selected period — streaks are lifetime',
    uniqueQuestions: 'Unique questions',
    correct: 'Correct',
    incorrect: 'Incorrect',
    avgAnswerTime: 'Avg. answer time',
    notRecorded: 'Not recorded',
    accuracyTrend: 'Accuracy trend',
    currentAccuracy: (pct: number) => `${pct}% current accuracy`,
    changePoints: (delta: number) =>
      delta >= 0 ? `+${delta} percentage points vs previous period` : `${delta} percentage points vs previous period`,
    noPriorPeriod: 'No data in the previous period for comparison',
    chartSummary: 'Accuracy trend summary',
    noChartData: 'No first-attempt data in this period',
    improvementAfterRetry: 'Improvement after retry',
    firstAttempt: 'First attempt',
    afterRevision: 'After revision',
    improvementPoints: (delta: number) =>
      delta >= 0 ? `+${delta} percentage points` : `${delta} percentage points`,
    mistakesCorrected: (count: number) => `${count} mistakes corrected`,
    cohortSample: (count: number) => `Based on ${count} retried questions`,
    retryLockedTitle: 'Not enough retry data yet',
    retryLockedHint: 'Retry previously missed questions to unlock this insight.',
    timeConsistency: 'Time & consistency',
    recordedAnswerTime: 'Recorded answer time',
    activeDays: 'Active days',
    currentStreak: 'Current streak',
    longestStreak: 'Longest streak',
    streakDays: (count: number) => `${count} days`,
    studyTimeChart: 'Study time (min)',
    studyTimeChartHint: 'From recorded answer durations',
    noTimeData: 'No recorded time in this period',
    practiceMix: 'Practice mix',
    difficultyLevel: 'Difficulty level',
    subjectMix: 'Subject distribution',
    examMixOmitted: 'Exam tags overlap — showing subject distribution instead',
    recentActivity: 'Recent practice activity',
    session: 'Activity',
    score: 'Score',
    accuracy: 'Accuracy',
    time: 'Time',
    actions: 'Actions',
    view: 'View',
    review: 'Review',
    noRecentActivity: 'No practice activity in this period',
    noAttempts: 'No practice data yet. Start practicing to see activity here.',
    browseSubjects: 'Browse subjects',
    loadError: 'Could not load activity data. Please try again.',
    retry: 'Retry',
    firstAttemptHint: 'First-attempt accuracy — retries not included',
    lifetimeMetric: 'Lifetime',
    periodMetric: 'Selected period',
    percentLabel: (pct: number) => `${pct}%`,
    attemptsOnDay: (count: number) => `${count} attempts`,
  } as const;
}

export function periodQueryValue(period: ActivityPeriodDays): string {
  return period === 'all' ? 'all' : String(period);
}
