import type { ProfileLanguage } from './profileCopy';

export type ProfileGoalsCopy = ReturnType<typeof getProfileGoalsCopy>;

export function getProfileGoalsCopy(language: ProfileLanguage) {
  if (language === 'hi') {
    return {
      title: 'लक्ष्य और सेटिंग्स',
      subtitle: 'अपने लक्ष्य, उपलब्धियाँ और सीखने की प्राथमिकताएँ प्रबंधित करें',
      studyGoals: 'अध्ययन लक्ष्य',
      editGoals: 'लक्ष्य संपादित करें',
      questions: 'प्रश्न',
      goalProgressNote: 'प्रगति में अद्वितीय प्रथम प्रयास गिने जाते हैं — पुनः प्रयास शामिल नहीं।',
      achieved: 'हासिल',
      examTarget: 'परीक्षा लक्ष्य',
      updateTarget: 'लक्ष्य अपडेट करें',
      noExamSelected: 'कोई लक्ष्य परीक्षा सेट नहीं',
      examUnavailable: 'चयनित परीक्षा उपलब्ध नहीं',
      readiness: 'तैयारी',
      readinessLocked: 'कम से कम 10 अद्वितीय प्रश्न पूरे करें।',
      achievements: 'उपलब्धियाँ',
      derivedMilestones: 'प्रदर्शित माइलस्टोन व्युत्पन्न हैं — संग्रहीत पुरस्कार नहीं।',
      nextMilestone: 'अगला माइलस्टोन',
      allMilestonesComplete: 'सभी कॉन्फ़िगर किए गए माइलस्टोन पूरे',
      peerComparison: 'साथियों से तुलना',
      peerLocked: 'साथियों से तुलना अभी उपलब्ध नहीं है।',
      peerHint: 'आपकी व्यक्तिगत प्रगति सीखने की अंतर्दृष्टि में उपलब्ध है।',
      profilePreferences: 'प्रोफ़ाइल और प्राथमिकताएँ',
      displayName: 'प्रदर्शित नाम',
      email: 'ईमेल',
      preferredLanguage: 'पसंदीदा भाषा',
      targetExam: 'लक्ष्य परीक्षा',
      membership: 'सदस्यता',
      practiceReminders: 'अभ्यास अनुस्मारक',
      profileVisibility: 'प्रोफ़ाइल दृश्यता',
      joined: 'शामिल',
      notAvailable: 'उपलब्ध नहीं',
      profilesNotPublic: 'प्रोफ़ाइल सार्वजनिक नहीं हैं',
      languageClientNote: 'भाषा इस डिवाइस पर सहेजी जाती है',
      editProfile: 'प्रोफ़ाइल संपादित करें',
      saveGoals: 'लक्ष्य सहेजें',
      saving: 'सहेजा जा रहा है…',
      saveError: 'लक्ष्य सहेजे नहीं जा सके। पुनः प्रयास करें।',
      close: 'बंद करें',
      loadError: 'लक्ष्य डेटा लोड नहीं हो सका। कृपया पुनः प्रयास करें।',
      retry: 'पुनः प्रयास',
      newUserHint: 'अभ्यास शुरू करें — लक्ष्य प्रगति यहाँ दिखेगी।',
      browseSubjects: 'विषय देखें',
      daily: 'दैनिक',
      weekly: 'साप्ताहिक',
      monthly: 'मासिक',
      goalRowLabel: (period: string, actual: number, target: number) =>
        `${period} — ${actual} / ${target} प्रश्न`,
      english: 'English',
      hindi: 'हिंदी',
    } as const;
  }

  return {
    title: 'Goals & Settings',
    subtitle: 'Manage your targets, milestones and learning preferences',
    studyGoals: 'Study goals',
    editGoals: 'Edit goals',
    questions: 'questions',
    goalProgressNote: 'Progress counts unique first attempts — retries not included.',
    achieved: 'Achieved',
    examTarget: 'Exam target',
    updateTarget: 'Update target',
    noExamSelected: 'No target exam set',
    examUnavailable: 'Selected exam unavailable',
    readiness: 'Readiness',
    readinessLocked: 'Complete at least 10 unique questions to unlock.',
    achievements: 'Achievements',
    derivedMilestones: 'Milestones shown are derived — not persisted awards.',
    nextMilestone: 'Next milestone',
    allMilestonesComplete: 'All configured milestones complete',
    peerComparison: 'Peer comparison',
    peerLocked: 'Peer comparison is not available yet.',
    peerHint: 'Your personal progress is available in Learning Insights.',
    profilePreferences: 'Profile & preferences',
    displayName: 'Display name',
    email: 'Email',
    preferredLanguage: 'Preferred language',
    targetExam: 'Target exam',
    membership: 'Membership',
    practiceReminders: 'Practice reminders',
    profileVisibility: 'Profile visibility',
    joined: 'Joined',
    notAvailable: 'Not available',
    profilesNotPublic: 'Profiles are not public',
    languageClientNote: 'Language is saved on this device',
    editProfile: 'Edit profile',
    saveGoals: 'Save goals',
    saving: 'Saving…',
    saveError: 'Could not save goals. Please try again.',
    close: 'Close',
    loadError: 'Could not load goals data. Please try again.',
    retry: 'Retry',
    newUserHint: 'Start practicing — goal progress will appear here.',
    browseSubjects: 'Browse subjects',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    goalRowLabel: (period: string, actual: number, target: number) =>
      `${period} — ${actual} of ${target} questions`,
    english: 'English',
    hindi: 'Hindi',
  } as const;
}
