import type { ProfileLanguage } from './profileCopy';

export function getProfileInsightsCopy(language: ProfileLanguage) {
  if (language === 'hi') {
    return {
      title: 'सीखने की अंतर्दृष्टि',
      subtitle: 'समझें कि आप क्या जानते हैं और आगे क्या पढ़ना है',
      subjectProgress: 'विषय प्रगति',
      subjectProgressHint: 'प्रथम प्रयास सटीकता — पुनः प्रयास शामिल नहीं',
      subjectLocked: 'इस विषय में प्रगति अनलॉक करने के लिए कम से कम 10 प्रश्न पूरे करें।',
      viewAllSubjects: 'सभी विषय देखें',
      coverage: 'कवरेज',
      topicsInPlan: 'योजना में विषय',
      completed: 'पूर्ण',
      inProgress: 'प्रगति में',
      notStarted: 'शुरू नहीं',
      noPlan: 'अभी कोई अध्ययन योजना नहीं है।',
      noPlanHint: 'लक्ष्य परीक्षा सेट करें या विषयों से अभ्यास शुरू करें।',
      setTargetExam: 'लक्ष्य परीक्षा सेट करें',
      chooseSubjects: 'विषय चुनें',
      topicProgressTitle: (subject: string) => `${subject} प्रगति`,
      topicProgressHint: 'सक्रिय विषयों में प्रथम-प्रयास कवरेज',
      topicLocked: 'अपर्याप्त डेटा',
      strongArea: 'मजबूत क्षेत्र',
      strongMetric: 'प्रथम-प्रयास सटीकता',
      strongSample: (count: number) => `${count} अद्वितीय प्रश्नों पर आधारित`,
      noStrongArea: 'अभी कोई मजबूत क्षेत्र नहीं मिला',
      noStrongHint: 'किसी विषय में कम से कम 10 प्रश्न पूरे करें।',
      practiceMixedQuiz: 'मिश्रित क्विज़ का अभ्यास',
      focusNext: 'अगला फोकस',
      focusMetric: 'प्रथम-प्रयास सटीकता',
      mistakesDue: (count: number) => `${count} गलतियाँ समीक्षा के लिए`,
      noFocus: 'अभी कोई फोकस क्षेत्र नहीं',
      noFocusHint: 'अभ्यास जारी रखें — कमजोर विषय यहाँ दिखेंगे।',
      practiceFocusTopic: 'फोकस विषय का अभ्यास',
      byDifficulty: 'कठिनाई के अनुसार',
      difficultyHint: 'प्रथम-प्रयास सटीकता',
      notEnoughData: 'पर्याप्त डेटा नहीं',
      loadError: 'अंतर्दृष्टि लोड नहीं हो सकी। कृपया पुनः प्रयास करें।',
      retry: 'पुनः प्रयास',
      noAttempts: 'अभी तक कोई अभ्यास डेटा नहीं। अंतर्दृष्टि देखने के लिए अभ्यास शुरू करें।',
      browseSubjects: 'विषय देखें',
      firstAttemptAccuracy: 'प्रथम-प्रयास सटीकता',
      topicCoverage: 'विषय कवरेज',
    } as const;
  }

  return {
    title: 'Learning Insights',
    subtitle: 'Understand what you know and what to study next',
    subjectProgress: 'Subject progress',
    subjectProgressHint: 'First-attempt accuracy — retries not included',
    subjectLocked: 'Complete at least 10 questions in this subject to unlock progress.',
    viewAllSubjects: 'View all subjects',
    coverage: 'Coverage',
    topicsInPlan: 'topics in plan',
    completed: 'Completed',
    inProgress: 'In progress',
    notStarted: 'Not started',
    noPlan: 'No study plan yet.',
    noPlanHint: 'Set a target exam or start practicing from Subjects.',
    setTargetExam: 'Set target exam',
    chooseSubjects: 'Choose subjects',
    topicProgressTitle: (subject: string) => `${subject} progress`,
    topicProgressHint: 'First-attempt coverage across active topics',
    topicLocked: 'Insufficient data',
    strongArea: 'Strong area',
    strongMetric: 'First-attempt accuracy',
    strongSample: (count: number) => `Based on ${count} unique questions`,
    noStrongArea: 'No strong area identified yet',
    noStrongHint: 'Complete at least 10 questions in a topic to unlock this insight.',
    practiceMixedQuiz: 'Practice mixed quiz',
    focusNext: 'Focus next',
    focusMetric: 'First-attempt accuracy',
    mistakesDue: (count: number) => `${count} mistakes due for revision`,
    noFocus: 'No focus area yet',
    noFocusHint: 'Keep practicing — weak topics will appear here.',
    practiceFocusTopic: 'Practice focus topic',
    byDifficulty: 'By difficulty',
    difficultyHint: 'First-attempt accuracy',
    notEnoughData: 'Not enough data',
    loadError: 'Could not load learning insights. Please try again.',
    retry: 'Retry',
    noAttempts: 'No practice data yet. Start practicing to see insights here.',
    browseSubjects: 'Browse subjects',
    firstAttemptAccuracy: 'First-attempt accuracy',
    topicCoverage: 'Topic coverage',
  } as const;
}

export type ProfileInsightsCopy = ReturnType<typeof getProfileInsightsCopy>;
