import type { StructuredTopicGroup } from '@/lib/geography/physicalGeographyData';

export const ENVIRONMENT_ECOLOGY_DATA: StructuredTopicGroup[] = [
  {
    id: 1,
    title: 'Ecology & Ecosystem Fundamentals | पारिस्थितिकी और पारितंत्र के मूल सिद्धांत',
    subtopics: [
      'Ecology: Meaning, Scope and Importance | पारिस्थितिकी: अर्थ, क्षेत्र और महत्व',
      'Environment vs Ecology vs Ecosystem | पर्यावरण बनाम पारिस्थितिकी बनाम पारितंत्र',
      'Components of Environment | पर्यावरण के घटक',
      'Biotic and Abiotic Factors | जैविक और अजैविक कारक',
      'Habitat and Ecological Niche | आवास और पारिस्थितिक आला',
      'Population, Community and Biome | जनसंख्या, समुदाय और बायोम',
      'Ecotone and Edge Effect | इकोटोन और किनारा प्रभाव',
      'Ecological Succession | पारिस्थितिक उद्वहन',
      'Ecological Balance and Stability | पारिस्थितिक संतुलन और स्थिरता',
      'Adaptation and Survival Strategies | अनुकूलन और जीवित रहने की रणनीतियाँ',
    ],
  },
  {
    id: 2,
    title: 'Ecosystem Structure & Function | पारितंत्र की संरचना और कार्य',
    subtopics: [
      'Ecosystem: Meaning and Types | पारितंत्र: अर्थ और प्रकार',
      'Producers, Consumers and Decomposers | उत्पादक, उपभोक्ता और अपघटक',
      'Autotrophs and Heterotrophs | स्वयंपोषी और परपोषी',
      'Trophic Levels | क्षुधा स्तर',
      'Energy Flow in Ecosystem | पारितंत्र में ऊर्जा प्रवाह',
      '10 Percent Law of Energy Transfer | ऊर्जा स्थानांतरण का 10 प्रतिशत नियम',
      'Nutrient Flow in Ecosystem | पारितंत्र में पोषक तत्व प्रवाह',
      'Ecosystem Homeostasis | पारितंत्र समस्थिति',
    ],
  },
  {
    id: 3,
    title: 'Food Chain, Food Web & Ecological Pyramids | खाद्य श्रृंखला, खाद्य जाल और पारिस्थितिक पिरामिड',
    subtopics: [
      'Food Chain: Grazing and Detritus | खाद्य श्रृंखला: चराई और अपमल',
      'Food Web | खाद्य जाल',
      'Trophic Interactions | क्षुधा संवाद',
      'Ecological Pyramid: Meaning | पारिस्थितिक पिरामिड: अर्थ',
      'Pyramid of Number | संख्या का पिरामिड',
      'Pyramid of Biomass | जैव द्रव्यमान का पिरामिड',
      'Pyramid of Energy | ऊर्जा का पिरामिड',
      'Inverted Ecological Pyramids | उलटे पारिस्थितिक पिरामिड',
      'Ecological Efficiency | पारिस्थितिक दक्षता',
    ],
  },
  {
    id: 4,
    title: 'Ecological Productivity | पारिस्थितिक उत्पादकता',
    subtopics: [
      'Primary Productivity | प्राथमिक उत्पादकता',
      'Gross Primary Productivity | सकल प्राथमिक उत्पादकता',
      'Net Primary Productivity | शुद्ध प्राथमिक उत्पादकता',
      'Secondary Productivity | द्वितीयक उत्पादकता',
      'Standing Crop and Biomass | स्थायी फसल और जैव द्रव्यमान',
      'Factors Affecting Productivity | उत्पादकता को प्रभावित करने वाले कारक',
      'Productivity in Forest Ecosystem | वन पारितंत्र में उत्पादकता',
      'Productivity in Grassland Ecosystem | घास के मैदान पारितंत्र में उत्पादकता',
      'Productivity in Aquatic Ecosystem | जलीय पारितंत्र में उत्पादकता',
      'Carrying Capacity | वहन क्षमता',
    ],
  },
  {
    id: 5,
    title: 'Biogeochemical Cycles | जैव-भू-रासायनिक चक्र',
    subtopics: [
      'Carbon Cycle | कार्बन चक्र',
      'Nitrogen Cycle | नाइट्रोजन चक्र',
      'Oxygen Cycle | ऑक्सीजन चक्र',
      'Water Cycle | जल चक्र',
      'Phosphorus Cycle | फॉस्फोरस चक्र',
      'Sulphur Cycle | सल्फर चक्र',
      'Nutrient Cycling | पोषक तत्व चक्रण',
      'Human Impact on Biogeochemical Cycles | जैव-भू-रासायनिक चक्रों पर मानव प्रभाव',
      'Linkage with Climate Change and Pollution | जलवायु परिवर्तन और प्रदूषण से संबंध',
    ],
  },
  {
    id: 6,
    title: 'Types of Ecosystems | पारितंत्र के प्रकार',
    subtopics: [
      'Forest Ecosystem | वन पारितंत्र',
      'Grassland Ecosystem | घास के मैदान पारितंत्र',
      'Desert Ecosystem | मरुस्थल पारितंत्र',
      'Freshwater Ecosystem | ताजा जल पारितंत्र',
      'Marine Ecosystem | समुद्री पारितंत्र',
      'Wetland Ecosystem | आर्द्रभूमि पारितंत्र',
      'Mangrove Ecosystem | सुंदरवन पारितंत्र',
      'Coral Reef Ecosystem | प्रवाल भित्ति पारितंत्र',
      'Estuarine and Island Ecosystem | मुखस्थलीय और द्वीप पारितंत्र',
    ],
  },
  {
    id: 7,
    title: 'Biodiversity Concepts | जैव विविधता की अवधारणाएँ',
    subtopics: [
      'Biodiversity: Meaning and Importance | जैव विविधता: अर्थ और महत्व',
      'Genetic Diversity | आनुवंशिक विविधता',
      'Species Diversity | प्रजाति विविधता',
      'Ecosystem Diversity | पारितंत्र विविधता',
      'Alpha, Beta and Gamma Diversity | अल्फा, बीटा और गामा विविधता',
      'Species Richness and Species Evenness | प्रजाति समृद्धि और प्रजाति समानता',
      'Biodiversity Values | जैव विविधता के मूल्य',
      'Threats to Biodiversity | जैव विविधता के खतरे',
    ],
  },
  {
    id: 8,
    title: 'Biodiversity Hotspots & Species Concepts | जैव विविधता हॉटस्पॉट और प्रजाति अवधारणाएँ',
    subtopics: [
      'Biodiversity Hotspots | जैव विविधता हॉटस्पॉट',
      'Indian Biodiversity Hotspots | भारतीय जैव विविधता हॉटस्पॉट',
      'Endemism | स्थानिकता',
      'Keystone Species | मुख्य प्रजाति',
      'Flagship Species | प्रतिनिधि प्रजाति',
      'Umbrella Species | छत्र प्रजाति',
      'Indicator Species | सूचक प्रजाति',
      'Foundation Species | आधार प्रजाति',
      'Invasive Alien Species | आक्रामक विदेशी प्रजातियाँ',
    ],
  },
  {
    id: 9,
    title: 'Forests & Wildlife Conservation | वन और वन्यजीव संरक्षण',
    subtopics: [
      'Forest Conservation | वन संरक्षण',
      'Wildlife Conservation | वन्यजीव संरक्षण',
      'In-situ Conservation | प्राकृतिक स्थान में संरक्षण',
      'Ex-situ Conservation | बाहरी स्थान में संरक्षण',
      'Wildlife Corridors | वन्यजीव गलियारे',
      'Human-Wildlife Conflict | मानव-वन्यजीव संघर्ष',
      'Community Participation in Conservation | संरक्षण में सामुदायिक भागीदारी',
      'Sacred Groves | पवित्र वन',
      'Joint Forest Management | संयुक्त वन प्रबंधन',
    ],
  },
  {
    id: 10,
    title: 'Protected Areas Network | संरक्षित क्षेत्र नेटवर्क',
    subtopics: [
      'National Parks | राष्ट्रीय उद्यान',
      'Wildlife Sanctuaries | वन्यजीव अभयारण्य',
      'Biosphere Reserves | जीवमंडल रिजर्व',
      'Conservation Reserves | संरक्षण रिजर्व',
      'Community Reserves | सामुदायिक रिजर्व',
      'Tiger Reserves | बाघ रिजर्व',
      'Elephant Reserves | हाथी रिजर्व',
      'Marine Protected Areas | समुद्री संरक्षित क्षेत्र',
      'Ramsar Sites | रामसर आर्द्रभूमि',
      'Eco-Sensitive Zones | पारिस्थितिक संवेदनशील क्षेत्र',
    ],
  },
  {
    id: 11,
    title: 'Species Conservation | प्रजाति संरक्षण',
    subtopics: [
      'IUCN Red List | IUCN लाल सूची',
      'Threatened Species | संकटग्रस्त प्रजातियाँ',
      'Vulnerable Species | संवेदनशील प्रजातियाँ',
      'Endangered Species | लुप्तप्राय प्रजातियाँ',
      'Critically Endangered Species | अत्यंत लुप्तप्राय प्रजातियाँ',
      'Extinct and Extinct in the Wild Species | विलुप्त और जंगल में विलुप्त प्रजातियाँ',
      'Species Recovery Programmes | प्रजाति पुनर्प्राप्ति कार्यक्रम',
      'Wildlife Census and Monitoring | वन्यजीव गणना और निगरानी',
    ],
  },
  {
    id: 12,
    title: 'Environmental Pollution | पर्यावरण प्रदूषण',
    subtopics: [
      'Air Pollution | वायु प्रदूषण',
      'Water Pollution | जल प्रदूषण',
      'Soil Pollution | मृदा प्रदूषण',
      'Noise Pollution | ध्वनि प्रदूषण',
      'Marine Pollution | समुद्री प्रदूषण',
      'Thermal Pollution | तापीय प्रदूषण',
      'Radioactive Pollution | रेडियोधर्मी प्रदूषण',
      'Acid Rain, Smog and Ozone Depletion | अम्ल वर्षा, धुंध और ओजोन क्षय',
      'Bioaccumulation, Biomagnification and Eutrophication | जैव संचय, जैव आवर्धन और अतिपोषण',
    ],
  },
  {
    id: 13,
    title: 'Waste Management | अपशिष्ट प्रबंधन',
    subtopics: [
      'Solid Waste Management | ठोस अपशिष्ट प्रबंधन',
      'Plastic Waste Management | प्लास्टिक अपशिष्ट प्रबंधन',
      'Biomedical Waste Management | जैव-चिकित्सीय अपशिष्ट प्रबंधन',
      'Hazardous Waste Management | खतरनाक अपशिष्ट प्रबंधन',
      'E-Waste Management | ई-अपशिष्ट प्रबंधन',
      'Waste Segregation and Processing | अपशिष्ट पृथक्करण और प्रसंस्करण',
      'Waste-to-Energy | अपशिष्ट से ऊर्जा',
      'Circular Economy and Extended Producer Responsibility | परिपत्र अर्थव्यवस्था और विस्तारित उत्पादक जिम्मेदारी',
    ],
  },
  {
    id: 14,
    title: 'Climate Change | जलवायु परिवर्तन',
    subtopics: [
      'Weather vs Climate | मौसम बनाम जलवायु',
      'Global Warming | वैश्विक ऊष्मीकरण',
      'Greenhouse Effect | ग्रीनहाउस प्रभाव',
      'Greenhouse Gases | ग्रीनहाउस गैसें',
      'Carbon Footprint and Carbon Sink | कार्बन पदचिह्न और कार्बन सिंक',
      'Climate Mitigation | जलवायु शमन',
      'Climate Adaptation | जलवायु अनुकूलन',
      'Net Zero, Carbon Market and Loss & Damage | शुद्ध शून्य, कार्बन बाजार और क्षति व हानि',
    ],
  },
  {
    id: 15,
    title: 'Environmental Governance, Laws & Agreements | पर्यावरण शासन, कानून और समझौते',
    subtopics: [
      'Environment Protection Act | पर्यावरण संरक्षण अधिनियम',
      'Wildlife Protection Act | वन्यजीव संरक्षण अधिनियम',
      'Forest Conservation Act | वन संरक्षण अधिनियम',
      'Biological Diversity Act | जैव विविधता अधिनियम',
      'Water Act and Air Act | जल अधिनियम और वायु अधिनियम',
      'Environmental Impact Assessment | पर्यावरण प्रभाव मूल्यांकन',
      'National Green Tribunal, CPCB and SPCBs | राष्ट्रीय हरित अधिकरण, CPCB और SPCB',
      'International Environmental Agreements | अंतर्राष्ट्रीय पर्यावरण समझौते',
    ],
  },
  {
    id: 16,
    title: 'Sustainable Development & Resource Management | सतत विकास और संसाधन प्रबंधन',
    subtopics: [
      'Sustainable Development and SDGs | सतत विकास और SDG',
      'Green Economy and ESG | हरित अर्थव्यवस्था और ESG',
      'Sustainable Agriculture and Sustainable Cities | सतत कृषि और सतत शहर',
      'Renewable and Non-Renewable Resources | नवीकरणीय और अनवीकरणीय संसाधन',
      'Natural Resource Conservation | प्राकृतिक संसाधन संरक्षण',
    ],
  },
  {
    id: 17,
    title: 'Current Environment & Ecology | वर्तमान पर्यावरण और पारिस्थितिकी',
    subtopics: [
      'Environmental Reports and Indices: Latest Editions | पर्यावरण रिपोर्ट और सूचकांक: नवीनतम संस्करण',
      'Species, Protected Areas and Reports in News | समाचार में प्रजातियाँ, संरक्षित क्षेत्र और रिपोर्ट',
      'Climate Summits, New Policies and Current Affairs | जलवायु शिखर सम्मेलन, नई नीतियाँ और समसामयिक मामले',
    ],
  },
];

export const ENVIRONMENT_ECOLOGY_PAGE_TITLE = {
  en: 'Environment & Ecology',
  hi: 'पर्यावरण और पारिस्थितिकी',
};

export const ENVIRONMENT_ECOLOGY_SECTION_LABEL = {
  en: 'Environment & Ecology Topics',
  hi: 'पर्यावरण और पारिस्थितिकी के विषय',
};
