import type { StructuredTopicGroup } from '@/lib/geography/physicalGeographyData';

export const INDIAN_GEOGRAPHY_DATA: StructuredTopicGroup[] = [
  {
    id: 1,
    title: 'Location & Extent of India | भारत का स्थान और विस्तार',
    subtopics: [
      'Geographical Location | भौगोलिक स्थिति',
      'Latitudinal & Longitudinal Extent | अक्षांशीय और देशांतरीय विस्तार',
      'Standard Meridian of India | भारत की मानक ध्रुवीय रेखा',
      'Indian Standard Time (IST) | भारतीय मानक समय (IST)',
      'Neighbouring Countries | पड़ोसी देश',
      'International Boundaries | अंतर्राष्ट्रीय सीमाएँ',
    ],
  },
  {
    id: 2,
    title: 'Physiographic Divisions | भौतिक विभाजन',
    subtopics: [
      'Himalayan Mountains | हिमालय पर्वत',
      'Northern Plains | उत्तरी मैदान',
      'Peninsular Plateau | प्रायद्वीपीय पठार',
      'Indian Desert | भारतीय मरुस्थल',
      'Coastal Plains | तटीय मैदान',
      'Islands | द्वीप',
      'Physiographic Significance | भौतिक महत्व',
    ],
  },
  {
    id: 3,
    title: 'Geological Structure of India | भारत की भू-वैज्ञानिक संरचना',
    subtopics: [
      'Geological Evolution | भू-वैज्ञानिक विकास',
      'Rock Systems | शैल प्रणालियाँ',
      'Plate Tectonic Setting | प्लेट विवर्तनिकी संदर्भ',
      'Mineral Belts | खनिज पट्टियाँ',
      'Seismic Zones | भूकंपीय क्षेत्र',
      'Volcanoes of India | भारत के ज्वालामुखी',
    ],
  },
  {
    id: 4,
    title: 'Drainage System | अपवाह तंत्र',
    subtopics: [
      'Himalayan Rivers | हिमालयी नदियाँ',
      'Peninsular Rivers | प्रायद्वीपीय नदियाँ',
      'River Basins | नदी बेसिन',
      'Lakes | झीलें',
      'Waterfalls | जलप्रपात',
      'Wetlands | आर्द्रभूमि',
      'River Linking Projects | नदी जोड़ परियोजनाएँ',
    ],
  },
  {
    id: 5,
    title: 'Climate of India | भारत की जलवायु',
    subtopics: [
      'Climate Controls | जलवायु नियंत्रक',
      'Seasons of India | भारत की ऋतुएँ',
      'Indian Monsoon | भारतीय मानसून',
      'Western Disturbances | पश्चिमी विक्षोभ',
      'Cyclones | चक्रवात',
      'Local Winds | स्थानीय पवन',
      'Climatic Regions | जलवायु क्षेत्र',
    ],
  },
  {
    id: 6,
    title: 'Soils of India | भारत की मृदाएँ',
    subtopics: [
      'Alluvial Soil | जलोढ़ मृदा',
      'Black Soil | काली मृदा',
      'Red & Yellow Soil | लाल और पीली मृदा',
      'Laterite Soil | लैटराइट मृदा',
      'Desert Soil | मरुस्थलीय मृदा',
      'Mountain Soil | पर्वतीय मृदा',
      'Soil Conservation | मृदा संरक्षण',
    ],
  },
  {
    id: 7,
    title: 'Natural Vegetation | प्राकृतिक वनस्पति',
    subtopics: [
      'Tropical Evergreen Forest | उष्णकटिबंधीय सदाबहार वन',
      'Deciduous Forest | पर्णपाती वन',
      'Thorn Forest | कंटीली वन',
      'Montane Forest | पर्वतीय वन',
      'Mangrove Forest | मैंगroव वन',
      'Grasslands | घास के मैदान',
      'Biosphere Reserves | जीवमंडल आरक्षित क्षेत्र',
    ],
  },
  {
    id: 8,
    title: 'Agriculture | कृषि',
    subtopics: [
      'Cropping Seasons | फसल चक्र',
      'Food Crops | खाद्य फसलें',
      'Cash Crops | नकदी फसलें',
      'Plantation Crops | बागान फसलें',
      'Irrigation | सिंचाई',
      'Green Revolution | हरित क्रांति',
      'Agricultural Regions | कृषि क्षेत्र',
      'Agricultural Challenges | कृषि की चुनौतियाँ',
    ],
  },
  {
    id: 9,
    title: 'Mineral Resources | खनिज संसाधन',
    subtopics: [
      'Metallic Minerals | धात्विक खनिज',
      'Non-Metallic Minerals | अधात्विक खनिज',
      'Atomic Minerals | परमाणु खनिज',
      'Major Mining Regions | प्रमुख खनन क्षेत्र',
      'Mineral Distribution | खनिज वितरण',
      'Mineral Conservation | खनिज संरक्षण',
    ],
  },
  {
    id: 10,
    title: 'Energy Resources | ऊर्जा संसाधन',
    subtopics: [
      'Coal | कोयला',
      'Petroleum | पेट्रोलियम',
      'Natural Gas | प्राकृतिक गैस',
      'Hydropower | जल विद्युत',
      'Nuclear Energy | परमाणु ऊर्जा',
      'Renewable Energy | नवीकरणीय ऊर्जा',
      'Power Projects | विद्युत परियोजनाएँ',
    ],
  },
  {
    id: 11,
    title: 'Industries | उद्योग',
    subtopics: [
      'Iron & Steel | लोहा और इस्पात',
      'Textile | वस्त्र',
      'Automobile | ऑटोमोबाइल',
      'IT Industry | सूचना प्रौद्योगिकी उद्योग',
      'Petrochemical | पेट्रो-रसायन',
      'Industrial Regions | औद्योगिक क्षेत्र',
      'Industrial Corridors | औद्योगिक कॉरिडोर',
    ],
  },
  {
    id: 12,
    title: 'Transport & Communication | परिवहन और संचार',
    subtopics: [
      'Roadways | सड़क मार्ग',
      'Railways | रेलवे',
      'Airways | वायु मार्ग',
      'Waterways | जलमार्ग',
      'Pipelines | पाइपलाइन',
      'Ports | बंदरगाह',
      'Communication Network | संचार नेटवर्क',
    ],
  },
  {
    id: 13,
    title: 'Population | जनसंख्या',
    subtopics: [
      'Population Distribution | जनसंख्या वितरण',
      'Population Density | जनसंख्या घनत्व',
      'Population Growth | जनसंख्या वृद्धि',
      'Census | जनगणना',
      'Migration | प्रवास',
      'Urbanization | शहरीकरण',
      'Demographic Dividend | जनसांख्यिकीय लाभांश',
    ],
  },
  {
    id: 14,
    title: 'Regional Geography | प्रादेशिक भूगोल',
    subtopics: [
      'North India | उत्तर भारत',
      'South India | दक्षिण भारत',
      'East India | पूर्व भारत',
      'West India | पश्चिम भारत',
      'Central India | मध्य भारत',
      'North-East India | पूर्वोत्तर भारत',
      'Union Territories | केंद्र शासित प्रदेश',
    ],
  },
  {
    id: 15,
    title: 'Disaster Geography | आपदा भूगोल',
    subtopics: [
      'Earthquakes | भूकंप',
      'Floods | बाढ़',
      'Drought | सूखा',
      'Cyclones | चक्रवात',
      'Landslides | भू-स्खलन',
      'Tsunami | सुनामी',
      'Disaster Management | आपदा प्रबंधन',
    ],
  },
  {
    id: 16,
    title: 'Indian Mapping | भारतीय मानचित्रण',
    subtopics: [
      'States & Capitals | राज्य और राजधानियाँ',
      'Important Rivers | महत्वपूर्ण नदियाँ',
      'Mountain Ranges | पर्वत श्रेणियाँ',
      'Passes | दर्रे',
      'National Parks | राष्ट्रीय उद्यान',
      'Major Cities | प्रमुख शहर',
      'Dams | बाँध',
      'Ports | बंदरगाह',
      'Important Locations | महत्वपूर्ण स्थान',
    ],
  },
  {
    id: 17,
    title: 'Contemporary Indian Geography | समकालीन भारतीय भूगोल',
    subtopics: [
      'Smart Cities | स्मार्ट सिटी',
      'Industrial Corridors | औद्योगिक कॉरिडोर',
      'Bharatmala | भारतमाला',
      'Sagarmala | सागरमाला',
      'Inland Waterways | अंतर्देशीय जलमार्ग',
      'Blue Economy | नीली अर्थव्यवस्था',
      'GIS & Remote Sensing | GIS और दूर संवेदन',
    ],
  },
];

export const INDIAN_GEOGRAPHY_PAGE_TITLE = {
  en: 'Indian Geography',
  hi: 'भारतीय भूगोल',
};

export const INDIAN_GEOGRAPHY_SECTION_LABEL = {
  en: 'Indian Geography Topics',
  hi: 'भारतीय भूगोल के विषय',
};
